### ISSUE TITLE
Couldn't use gpu for training

### ISSUE THREAD

**Issue by gbs2025** [rezaakb/pinns-torch#14]
Thanks for sharing this great project.
I just cloned the whole project to my pc,installed the libs via 'requirements.txt'.
When i'm trying the 'train.py' in 'examples\schrodinger'.the logs says couldn't find gpu and code just use cpu by default.
Meanwhile the `accelerator` in 'config.yaml' is `gpu`.
btw my gpu is gtx1060,i tried same thing on other pc with rtx4090 and have the same problem.

**Comment by rezaakb** [comment]
Hello,

There is a possibility that your Torch installation is not recognizing the GPU. You can test it with the following code:

```python
import torch
print(torch.cuda.is_available())
```

If it returns False, please try reinstalling Torch by following the instructions on their official [website](https://pytorch.org/get-started/locally/).

**Comment by gbs2025** [comment]
@rezaakb 
It works,thanks a lot!
