### ISSUE TITLE
Demo example in tutorial did not provide expected result

### ISSUE THREAD

**Issue by PepperXZC** [rezaakb/pinns-torch#6]
I just directly cloned this repository, had virtual env setup and ran `tutorials/0-Schrodinger.ipynb`, but the resulted prediction did not reach convergence. Is there any additional setting should be done or any hyperparameters?
![image](https://github.com/rezaakb/pinns-torch/assets/103398581/91701ee0-ce71-4236-bb51-922b22c36411)

**Comment by rezaakb** [comment]
Yes, please increase the value of `max_epochs` in the training configuration. For instance:
`
trainer = pl.Trainer(accelerator='cpu', devices=1, max_epochs=60000)
`

**Comment by PepperXZC** [comment]
Thanks for your patience!
